@host = http://localhost:8080

//put {{host}}/recipes/c587e8ug10l0epmn187g
post {{host}}/recipes
Content-Type: application/json

{
  "name": "swizzy pizza",
  "tags" : ["italian", "pizza", "dinner"],
  "ingredients": [
    "pizza dough",
    "tomato sauce",
    "olive oil",
    "7 ounces fresh mozzarella cheese, cut into 1/2-inch cubes",
    "5 - 6 large fresh basil leaves"
  ],
  "instructions": []
}
###
delete {{host}}/recipes/c587h7mg10l0epmn1880
###
get {{host}}/recipes/search?tag=italian
